name: Master Fermi Summer School NB Testing  notebooks.
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  schedule:
    # Run only Friday morning starting at 1am EST
    - cron: '0 1 * * 5'
      timezone: 'America/New_York'

jobs:
  conda-ci:
    runs-on: ${{ matrix.runner }}
    name: "Master Fermi Summer Schooli NB Testing- ${{ matrix.pixi-platform }} "
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        include:
          - pixi-platform: linux-64
            runner: ubuntu-24.04
          - pixi-platform: linux-aarch64
            runner: ubuntu-24.04-arm
          - pixi-platform: osx-64
            runner: macos-15-intel
          - pixi-platform: osx-arm64
            runner: macos-15

    steps:
    # 1. Check out the source code
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Checkout repo
      uses: actions/checkout@v6
      with:
         ref: ${{github.ref_name}} #reset_checkout_fixes checkout_fixes master

    - name: Conda environment creation and activation
      uses: Wandalen/wretry.action@master
      with:
        action: conda-incubator/setup-miniconda@v4
        with: |
          conda-remove-defaults: true
          python-version: 3.12.*
          activate-environment: testing-jupyter
          environment-file: environments/fermitools-testing-jupyter-nbs.yml
          auto-update-conda: false
          auto-activate: false
          show-channel-urls: true
        attempt_limit: 3
        attempt_delay: 2000

    - name: Run notebooks as tests with nbmake
      id: run_jupyter_notebooks
      continue-on-error: ${{ fromJSON(vars.CONTINUE_ON_ERROR || 'false') }}  # Default is to fail at first error
      # Execute nbmake with pytest.
      # The --nbmake flag tells pytest to look for notebooks.
      # You can specify a directory like `notebooks/` or a pattern.
      run: |
        echo "Run tests testing-jupyter"
        echo "TESTING BRANCH  ${{ github.ref_name }}"
        # pip install git+https://github.com/fermiPy/fermipy.git
        pip install fermipy
        mkdir -p "${{ github.workspace }}/shared-testing/"
        cd "${{ github.workspace }}/shared-testing/"
        # git clone "https://github.com/fermi-lat/AnalysisThreads.git"
        git clone "https://github.com/FermiSummerSchool/fermi-summer-school.git"
        mkdir -p test_results

        cd fermi-summer-school
        # pytest -n auto --nbmake --nbmake-timeout=3000 --junitxml=../test_results/data_quicklook_result.xml -vv Data_Exploration/*.ipynb
        pytest -n auto  --nbmake --nbmake-timeout=3000 --junitxml=d2ata_quicklook_result.xml -vv Data_Exploration/Data_QuickLook.ipynb
        pytest -n auto --nbmake --nbmake-timeout=3000 --junitxml=../test_results/find_source_results.xml -vv Advanced_Topics/FindSource/*.ipynb

        # fails with 95 
        # Need for Likelihood_Advanced tests to run:
        wget https://fermi.gsfc.nasa.gov/science/mtgs/summerschool/2021/fermipyTutorialData.tgz
        tar xf fermipyTutorialData.tgz
        mv data ./Likelihood_Advanced
 
        pytest -n auto --nbmake --nbmake-timeout=4000 --junitxml=../test_results/fss_like_adv_fermipy_result.xml -vv Likelihood_Advanced/Likelihood_With_fermiPy.ipynb
        pytest -n auto --nbmake --nbmake-timeout=4000 --junitxml=../test_results/fss_like_adv_curvature_result.xml -vv Likelihood_Advanced/Curvature\ Test.ipynb
        pytest -n auto --nbmake --nbmake-timeout=6000 --junitxml=../test_results/fss_like_adv_lightcurve_result.xml -vv Likelihood_Advanced/Lightcurve.ipynb
        pytest -n auto --nbmake --nbmake-timeout=4000 --junitxml=../test_results/fss_like_adv_sed_result.xml -vv Likelihood_Advanced/SED\ Stuff.ipynb

        pytest -n auto --nbmake --nbmake-timeout=3000 --junitxml=../test_results/data_quicklook_result.xml -vv Data_Exploration/*.ipynb
        # pytest -n auto  --nbmake --nbmake-timeout=3000 --junitxml=d2ata_quicklook_result.xml -vv Data_Exploration/Data_QuickLook.ipynb
        pytest -n auto --nbmake --nbmake-timeout=3000 --junitxml=../test_results/find_source_results.xml -vv Advanced_Topics/FindSource/*.ipynb


        # --ignore=path/to/ignored_dir -n auto -vv
        # pytest --nbmake --nbmake-timeout=10000  --junitxml=../../test_results/most_jupyter_results.xml  **/*.ipynb
        # pytest --junitxml=../../test_results/most_jupyter_results.xml --nbmake --nbmake-timeout=10000 -n auto -vv  '*/*.ipynb'

    # The layout for this reporting action works. Not sure if there is something better, but it does a good job for us.
    - name: Publish Test Results Linux
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: runner.os == 'Linux'
      with:
        check_name: "Test Results: Conda Baseline ${{ matrix.runner }}"
        files: |
           ${{ github.workspace }}/shared-testing/test_results/*.xml

    - name: Publish Test Results OSX
      uses: EnricoMi/publish-unit-test-result-action/macos@v2
      if: runner.os == 'macOS'
      with:
        check_name: "Test Results: Conda Baseline ${{ matrix.runner }}"
        files: |
           ${{ github.workspace }}/shared-testing/test_results/*.xml
